spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicate:
            - PATH=/customers/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicate:
            - PATH=/orders/**
        - id: order-product-service
          uri: lb:http://ORDER-SERVICE
          predicate:
            - PATH=/order-products/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicate:
            - PATH=/products/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicate:
            - PATH=/payments/**
server:
  port: 9099