spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-payment-details
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: http://localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: payment:com.santho.ecommerce.dtos.PaymentNotificationRequest
server:
  port: 8084